### ISSUE TITLE
Страница с описанием ролей на сайте

### ISSUE THREAD

**Issue by WhiteCloud21** [WhiteCloud21/DiscordMafia#24]

**Comment by bikeroleg** [comment]
Должна ли она открываться по команде или сразу в начале игры?

**Comment by WhiteCloud21** [comment]
Уточнил в заголовке, чтобы вопросов не возникало. Просто будет в меню на сайте что-то вроде раздела помощи.

**Comment by bikeroleg** [comment]
Да, раздел помощи будет кстати.
